import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-4">
          <Link className="p-3" href="/">
            홈
          </Link>
          {children}
          <Link className="p-3" href="/main">
            메인
          </Link>

          <Link className="p-3" href="/delay">
            딜레이 컴포넌트
          </Link>
        </div>
      </body>
    </html>
  );
}
